version: '2'
services:
   logstash:
     image: logstash
     volumes:
       - ./logstash:/config-dir
     command: [ -f, /config-dir/logstash.conf ]
     depends_on:
       - elasticsearch

   elasticsearch:
     image: elasticsearch

   kibana:
     image: kibana
     environment:
       ELASTICSEARCH_URL: http://elasticsearch:9200
     ports:
       - "5601:5601"
     depends_on:
       - elasticsearch
